### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by Minemetero** [kdxhub/Pages-md-reRender#1]
1.打开Discussion供我讲废话
2.这网页一言难尽啊,我多次怀疑是我的Dark Reader忘关了(配色太丑了啊)
3.这注释。。加的好，下次还是别加了
![image_2024-10-26_173014549](https://github.com/user-attachments/assets/c0d746e1-0db5-427c-9067-9a6700c16de0)
4.啊我的docs你肿么那么臃肿啊
![image_2024-10-26_173347770](https://github.com/user-attachments/assets/696be634-4574-4514-ae7a-09fda687f46a)

**Comment by Minemetero** [comment]
还有一句废话
https://kdxiaoyi.top <- 这个域名你花了多少钱啊

**Comment by kdxhub** [comment]
感谢反馈

> 2.这网页一言难尽啊,我多次怀疑是我的Dark Reader忘关了(配色太丑了啊)

本项目基于apprat/Sober二次创作，Sober是一个Material Design UI库；默认配色是Sober自带的配色，可以通过[配色生成工具](https://soberjs.com/style/theme-builder)来修改。

> 3.这注释。。加的好，下次还是别加

目前正在迁移这些说明内容到[文档](https://kdxiaoyi.top/Pages-md-reRender/global-conf)中

> 4.啊我的docs你肿么那么臃肿啊

严格意义上讲，这并不是文档文件夹，而是Github Pages文件夹。
